### PR TITLE
Usabiltity changes to QRCode Scanning Screen

### PR DESCRIPTION
**Pull request by JasonIsAzn**
### Overview
- Add a zoom option
- Remove invalid qrcode checks. This will help when  officers have an external qrcode next to our qrcode
- ~~Add a manual button to sign in/sign out (UI wise i thought this would be cool? opinions wanted)~~
- Keep automatic navigation and added ui feedback 

### Test
- Test Zoom feature
- Ensure qrcode scanner still works

### CODE REVIEW

**Review by mestrada03 — CHANGES_REQUESTED** [review]
Check the Zoom in/Zoom out functionality. Seems that it works, just not enough to the point where it is noticeable. Could be a phone specific issue as well.

**Comment by JasonIsAzn** [comment]
Attempting to fix zoom function. Need testing

**Comment by JasonIsAzn** [comment]
completely removed zoom feature, may look into this more in the future. 
Zoom feauture isn't nesserily needed after removing invalid scans. Now when we have qrcode side by side the shpe one will be detected as intended.  
The only reason why we need zoom feature is for member far away from the screen, for this reason only we should still look into zoom feature.

**Review by mestrada03 — APPROVED** [review]
lgtm

**Pull request merged**
